---
- name: Intro to Dictionaries 
  hosts: localhost
  gather_facts: no

  vars:
    configA: exampleA.cfg #var mapped to str
    configB: exampleB.cfg #var mapped to str
    licensetypes:         #var mapped to a list of strs
      opentypes:
         - apatche2.0
         - gnu public license (GPL)
         - mit license
         - mozilla public license 
      paytypes:
         - windows 
         - redhat
         - apple

  tasks:
     - name: Recall a key value pair mapping 
       debug: 
         var: configA

     - name: Recall a key value where the value is a list
       debug: 
         var: licensetypes.opentypes #returns a list of license types 

     - name: 
       debug: 
         var: licensetypes.opentypes[2] #returns mit license

     - name: 
       debug: 
         var: licensetypes.paytypes[0] #return windows 



